[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pymisp>=2.5.17",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
